# Generated by Django 5.2.7 on 2025-11-08 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_chathistory12_chat_chatbot14_chathistory14_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory14',
            name='chat',
        ),
        migrations.CreateModel(
            name='Chatbot12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('timestamp_parent', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot14', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatHistory12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=5)),
                ('message', models.CharField(max_length=2000000)),
                ('timestamp_child', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChatHistory14', to='chatbot.chatbot12')),
            ],
            options={
                'ordering': ['-timestamp_child'],
            },
        ),
        migrations.DeleteModel(
            name='Chatbot14',
        ),
        migrations.DeleteModel(
            name='ChatHistory14',
        ),
    ]
