# Generated by Django 5.2.7 on 2025-11-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_love_blog_comment_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='comment_flag',
            field=models.IntegerField(default=0),
        ),
    ]
