# Generated by Django 5.2.7 on 2025-11-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_commentlike_comment_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='comment_flag',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
